version: '3'
services:
  app: 
    container_name: app
    restart: always
    build: ./app/
    ports:
      - '3001:3000'
    networks: 
      - appnetwork
    stdin_open: true
    tty: true
  api:
    container_name: api
    restart: always
    build: ./service/
    ports:
      - '3000:3000'
    links:
      - redis-server
      - mongodb
    networks: 
      - appnetwork
    stdin_open: true
    tty: true
    environment:
      MONGO_HOST: app-mongo
      MONGO_PORT: 27017
  mongodb:
    container_name: app-mongo
    image: 'mongo:4'
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - app-mongodb:/data/db
    networks: 
      - appnetwork
    stdin_open: true
    tty: true
  redis-server:
    container_name: app-redis
    image: 'redis:5'
    ports:
      - "6380:6379"
    restart: always
    networks: 
      - appnetwork
    stdin_open: true
    tty: true
networks:
  appnetwork:
    driver: bridge

volumes:
  app-mongodb:
